---
## Role Variables
- name: (COMMON) Determine unique package names for Debian OS family
  set_fact:
    dns_tools: "dnsutils"
  when: ansible_os_family == "Debian"

- name: (COMMON) Determine unique package names for Red Hat OS family
  set_fact:
    dns_tools: "bind-utils"
  when: ansible_os_family == "RedHat"

- name: (COMMON) Determine NTP/NTPD service name for Debian OS family
  set_fact:
    ntp_daemon: "ntp"
  when: ansible_os_family == "Debian"

- name: (COMMON) Determine NTP/NTPD name for Red Hat OS family
  set_fact:
    ntp_daemon: "ntpd"
  when: ansible_os_family == "RedHat"

- name: (COMMON) Determine syslog file name for Debian OS family
  set_fact:
    syslog_file: "/etc/logrotate.d/rsyslog"
  when: ansible_os_family == "Debian"

- name: (COMMON) Determine syslog file name for Red Hat OS family
  set_fact:
    syslog_file: "/etc/logrotate.d/syslog"
  when: ansible_os_family == "RedHat"

## Actions
- name: (COMMON) Set the correct timezone
  timezone:
    name: "{{ timezone }}"

- name: (COMMON) Set the hostname
  hostname:
    name: "{{ hostname }}"

- name: (COMMON) Write the hostname to the hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.0.1'
    line: '127.0.0.1 localhost {{ hostname }}'
    owner: root
    group: root
    mode: 0644

- name: (COMMON) Install essential packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - sudo
    - ntp
    - net-tools
    - curl
    - "{{ dns_tools }}"
    - git
    - unzip
    - moreutils
    - screen
    - rsync
    - ncdu
    - vim
    - iperf
    - pwgen
    - nano
    - tmux

- name: (COMMON) Ensure ntp starts at boot
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes

- name: (COMMON) Configure logrotate to include custom cron folder
  lineinfile:
    path: "{{ syslog_file }}"
    insertafter: '^/var/log/messages'
    line: /var/log/cron/*.log

- name: (COMMON) Configure logrotate to include custom cron folder
  file:
    path: /var/log/cronjobs
    state: directory
    owner: root
    group: root
    mode: 0750
